ktor:
  application:
    modules:
      - ru.emi.ApplicationKt.module
  deployment:
    port: 8080
#    rootPath: /api
    connectionGroupSize: 2
    workerGroupSize: 20
    callGroupSize: 10
    shutdownGracePeriod: 2000
    shutdownTimeout: 3000

postgres:
  url: ${POSTGRES_URL}
  user: ${POSTGRES_USER}
  password: ${POSTGRES_PASSWORD}
  driverClassName: org.postgresql.Driver

keycloak:
  uri: ${KEYCLOAK_URL}
  realm: ${KEYCLOAK_REALM}
  user-name-attribute: preferred_username
  client-id: ${KEYCLOAK_CLIENT_ID}
  client-secret: ${KEYCLOAK_CLIENT_SECRET}
  authorization-grant-type: authorization_code
  scope: openid

app:
  name: scheduler
  version: 0.0.1
  group: ru.emi
